### ISSUE TITLE
X-axis scale is way off

### ISSUE THREAD

**Issue by Emerassi** [Hyporos/maple-symbols#9]
![image](https://github.com/Hyporos/maple-symbols/assets/78173681/31eaed10-9851-4425-a6d3-f8198c515aaf)

See example picture.  An equal distance is sometimes only 3 days and sometimes it can be 11.  The result from this is that the graph ends up displaying a very steady slope even though every time a symbol levels up it the slope should get a little flatter.

**Comment by Hyporos** [comment]
Hey Emerassi, you make a pretty good point here.

With the current setup, each tick is correlated with a date that a symbol will level up on. The other option, as you mention (I believe) would be to have each tick set to fixed dates in between today and the final level up date.

Let me show you a few examples of both:

Type 1 - Cernium (level 1)
![image](https://github.com/Hyporos/maple-symbols/assets/59734777/2b44f3a0-4001-42e8-b2e9-9c87ee964f11)

Type 2 - Cernium (level 1)
![image](https://github.com/Hyporos/maple-symbols/assets/59734777/a240e158-5b33-4a2f-9809-4ac5d92df605)

Type 1 - Cernium (level 1) Arcus (level 4) Odium (level 5) Shangri-La (level 3) Arteria (level 7) Carcion (level 8)
![image](https://github.com/Hyporos/maple-symbols/assets/59734777/15e870ae-9da5-4a4b-8052-a22f32d9df08)

Type 2 - Cernium (level 1) Arcus (level 4) Odium (level 5) Shangri-La (level 3) Arteria (level 7) Carcion (level 8)
![image](https://github.com/Hyporos/maple-symbols/assets/59734777/5d7b3658-ae5e-4d1d-be30-d1077e886673)

Though the slope is not perfectly linear on Arcane Symbols when more than one levels up on the same date, it's still pretty linear for the most part. 

I suppose you can see it as two different, valid ways of viewing the graph. With the former looking nicer and being easier on the eyes, and the latter having a more detailed X Axis thus helping you gauge the progression better.

I've received opinions from a couple of people, and they also agree that both options have their advantages. 

I'll probably end up making this a toggle, being able to switch from the linear graph to the other one, with the default being the linear as it looks nicer and is easier to understand.

Let me know what you think! Thanks

**Comment by Emerassi** [comment]
Thanks for looking into it and replying.  No surprise probably but I like
the second one better!  Also WOW I did not realize just -how much- it
slooooooows down near the end of a symbol.  Makes me glad I'm personally
still dealing with Arcane Symbols and haven't hit the Sacred Force ones yet!

Emerassi

**Comment by Hyporos** [comment]
> Author

Np! Now you should be able to swap between both the linear and exponential graphs. Thanks for the input!

And yeah.... sacred is a real grind. But it was much worse before

**Comment by Emerassi** [comment]
Love the new option, nice work!
